<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        @page {
            margin: 18px 18px 22px 18px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111;
        }

        .sheet {
            border: 1px solid #cfcfcf;
            padding: 12px 12px 10px;
        }

        .toprow {
            width: 100%;
            border-bottom: 1px solid #cfcfcf;
            padding-bottom: 8px;
            margin-bottom: 10px;
        }

        .toprow td {
            vertical-align: middle;
        }

        .logo {
            width: 58px;
            height: 58px;
            object-fit: contain;
        }

        .center-head {
            text-align: center;
            line-height: 1.2;
        }

        .center-head .dept {
            font-size: 11px;
            font-weight: 700;
            letter-spacing: .3px;
        }

        .center-head .office {
            font-size: 13px;
            font-weight: 800;
            letter-spacing: .4px;
            margin-top: 2px;
        }

        .center-head .city {
            font-size: 11px;
            font-weight: 700;
            margin-top: 2px;
        }

        .meta-wrap {
            width: 100%;
            margin-bottom: 12px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-table td {
            border: 1px solid #d6d6d6;
            padding: 6px 8px;
            vertical-align: top;
        }

        .meta-label {
            width: 160px;
            font-weight: 700;
            background: #f7f8fb;
        }

        .report-title {
            font-size: 14px;
            font-weight: 800;
            margin: 0;
        }

        .sub {
            font-size: 11px;
            color: #444;
            margin: 2px 0 6px;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.report th,
        table.report td {
            border: 1px solid #d6d6d6;
            padding: 6px 8px;
            vertical-align: top;
        }

        table.report th {
            background: #f3f6ff;
            font-weight: 700;
        }

        .muted {
            color: #666;
        }
    </style>
</head>

<body>
    <div class="sheet">

        {{-- ===== HEADER (3 LOGOS) ===== --}}
        <table class="toprow" cellspacing="0" cellpadding="0">
            <tr>
                <td style="width:70px;">
                    @php $deped = public_path('images/deped.png'); @endphp
                    @if (file_exists($deped))
                        <img class="logo" src="{{ $deped }}">
                    @endif
                </td>

                <td style="width:70px;">
                    @php $bagong = public_path('images/bagong-pilipinas.png'); @endphp
                    @if (file_exists($bagong))
                        <img class="logo" src="{{ $bagong }}">
                    @endif
                </td>

                <td style="width:70px; text-align:right;">
                    @php $seal = public_path('images/sdo-seal.png'); @endphp
                    @if (file_exists($seal))
                        <img class="logo" src="{{ $seal }}">
                    @endif
                </td>

                <td class="center-head">
                    <div class="dept">DEPARTMENT OF EDUCATION</div>
                    <div class="office">SCHOOLS DIVISION OF ROXAS CITY</div>
                    <div class="city">SDO eFiles</div>
                </td>
            </tr>
        </table>

        {{-- ===== META ===== --}}
        <div class="meta-wrap">
            <p class="report-title">Audit Logs Report</p>
            <p class="sub">System activity logs (view, upload, download, delete, restore, trash)</p>

            <table class="meta-table">
                <tr>
                    <td class="meta-label">Generated</td>
                    <td>{{ $meta['generated_at'] ?? '—' }}</td>
                </tr>

                <tr>
                    <td class="meta-label">Generated By</td>
                    <td>{{ $meta['generated_by'] ?? 'System' }}</td>
                </tr>

                <tr>
                    <td class="meta-label">Total Records</td>
                    <td>{{ $meta['count'] ?? 0 }}</td>
                </tr>
            </table>
        </div>

        {{-- ===== REPORT TABLE ===== --}}
        <table class="report">
            <thead>
                <tr>
                    <th style="width:130px;">Date</th>
                    <th>User</th>
                    <th style="width:80px;">Role</th>
                    <th style="width:90px;">Action</th>
                    <th>Document</th>
                    <th>Document Owner</th>
                    <th style="width:110px;">IP Address</th>
                </tr>
            </thead>
            <tbody>
                @forelse($logs as $log)
                    @php
                        $ownerEmployee = $log->employee ?: optional($log->document)->employee;

                        if ($ownerEmployee) {
                            $firstMiddle = trim(
                                collect([$ownerEmployee->first_name, $ownerEmployee->middle_name])
                                    ->filter()
                                    ->implode(' '),
                            );

                            $owner = trim(
                                collect([
                                    $ownerEmployee->last_name ? $ownerEmployee->last_name . ',' : null,
                                    $firstMiddle,
                                ])
                                    ->filter()
                                    ->implode(' '),
                            );
                        } else {
                            $owner = '—';
                        }
                    @endphp
                    <tr>
                        <td>{{ optional($log->created_at)->format('Y-m-d H:i') }}</td>
                        <td>
                            {{ $log->user->name ?? 'System' }}<br>
                            <span class="muted">{{ $log->user->email ?? '' }}</span>
                        </td>
                        <td class="muted">{{ ucfirst($log->user->role ?? '—') }}</td>
                        <td>{{ ucfirst($log->action) }}</td>
                        <td>{{ $log->document->title ?? '—' }}</td>
                        <td>{{ $owner }}</td>
                        <td class="muted">{{ $log->ip ?? '—' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="muted">No audit logs found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</body>

</html>
