<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        @page {
            margin: 18px 18px 22px 18px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111;
        }

        .sheet {
            border: 1px solid #cfcfcf;
            padding: 12px 12px 10px;
        }

        /* ---------- header ---------- */
        .toprow {
            width: 100%;
            border-bottom: 1px solid #cfcfcf;
            padding-bottom: 8px;
            margin-bottom: 10px;
        }

        .toprow td {
            vertical-align: middle;
        }

        .logo {
            width: 58px;
            height: 58px;
            object-fit: contain;
        }

        .center-head {
            text-align: center;
            line-height: 1.2;
        }

        .center-head .dept {
            font-size: 11px;
            font-weight: 700;
            letter-spacing: .3px;
        }

        .center-head .office {
            font-size: 13px;
            font-weight: 800;
            letter-spacing: .4px;
            margin-top: 2px;
        }

        .center-head .city {
            font-size: 11px;
            font-weight: 700;
            margin-top: 2px;
        }

        /* ---------- meta ---------- */
        .meta-wrap {
            width: 100%;
            margin-bottom: 12px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-table td {
            border: 1px solid #d6d6d6;
            padding: 6px 8px;
            vertical-align: top;
        }

        .meta-label {
            width: 160px;
            font-weight: 700;
            background: #f7f8fb;
        }

        .report-title {
            font-size: 14px;
            font-weight: 800;
            margin: 0;
        }

        .sub {
            font-size: 11px;
            color: #444;
            margin: 2px 0 6px;
        }

        /* ---------- table ---------- */
        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table.report th,
        table.report td {
            border: 1px solid #d6d6d6;
            padding: 6px 8px;
            vertical-align: top;
        }

        table.report th {
            background: #f3f6ff;
            font-weight: 700;
        }

        .muted {
            color: #666;
        }

        .right {
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="sheet">

        {{-- ===== HEADER ===== --}}
        <table class="toprow" cellspacing="0" cellpadding="0">
            <tr>
                <td style="width:70px;">
                    @php $deped = public_path('images/deped.png'); @endphp
                    @if (file_exists($deped))
                        <img class="logo" src="{{ $deped }}">
                    @endif
                </td>

                <td style="width:70px;">
                    @php $bagong = public_path('images/bagong-pilipinas.png'); @endphp
                    @if (file_exists($bagong))
                        <img class="logo" src="{{ $bagong }}">
                    @endif
                </td>

                <td style="width:70px; text-align:right;">
                    @php $seal = public_path('images/sdo-seal.png'); @endphp
                    @if (file_exists($seal))
                        <img class="logo" src="{{ $seal }}">
                    @endif
                </td>
                <td class="center-head">
                    <div class="dept">DEPARTMENT OF EDUCATION</div>
                    <div class="office">SCHOOLS DIVISION OF ROXAS CITY</div>
                    <div class="city">SDO eFiles</div>
                </td>

            </tr>
        </table>


        {{-- ===== META ===== --}}
        <div class="meta-wrap">
            <p class="report-title">Employee Records Report</p>
            <p class="sub">Generated employee listing based on selected filters</p>

            <table class="meta-table">
                <tr>
                    <td class="meta-label">Generated</td>
                    <td>{{ $meta['generated_at'] ?? '—' }}</td>
                </tr>

                <tr>
                    <td class="meta-label">Generated By</td>
                    <td>
                        {{ $meta['generated_by'] ?? 'System Administrator' }}
                    </td>
                </tr>

                <tr>
                    <td class="meta-label">Total Records</td>
                    <td>{{ $meta['count'] ?? 0 }}</td>
                </tr>

                <tr>
                    <td class="meta-label">Filters</td>
                    <td>
                        Department:
                        <strong>{{ $meta['filters']['department'] ?? 'All' }}</strong> |
                        Position:
                        <strong>{{ $meta['filters']['position'] ?? 'All' }}</strong> |
                        Years:
                        <strong>{{ $meta['filters']['years'] ?? 'All' }}</strong> |
                        Search:
                        <strong>{{ $meta['filters']['q'] ?? '—' }}</strong>
                    </td>
                </tr>
            </table>
        </div>

        {{-- ===== REPORT TABLE ===== --}}
        <table class="report">
            <thead>
                <tr>
                    <th style="width:90px;">Employee #</th>
                    <th>Name</th>
                    <th style="width:140px;">Position</th>
                    <th style="width:220px;">School/Office</th>
                    <th style="width:140px;">Date Hired</th>
                    <th style="width:120px;" class="right">Years Employed</th>
                </tr>
            </thead>
            <tbody>
                @forelse($rows as $r)
                    <tr>
                        <td>{{ $r['employee_no'] }}</td>
                        <td>{{ $r['name'] }}</td>
                        <td class="muted">{{ $r['position'] }}</td>
                        <td class="muted">{{ $r['department'] }}</td>
                        <td class="muted">{{ $r['date_hired'] }}</td>
                        <td class="right">{{ $r['years'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="6" class="muted">
                            No records found for the selected filters.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</body>

</html>
